# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'winvestor_noexp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for winvestor_noexp

  pod 'libPusher', git: 'https://github.com/pusher/libPusher.git', branch: 'push-notifications'

end

