export const FETCH_PUBLIC_NEWS = 'FETCH_PUBLIC_NEWS';
export const FETCH_PUBLIC_NEWS_FAILED = 'FETCH_PUBLIC_NEWS_FAILED';
export const FETCH_PUBLIC_NEWS_SUCCESS = 'FETCH_PUBLIC_NEWS_SUCCESS';
export const LOAD_LOCAL_PUBLIC_NEWS_SUCCESS = 'LOAD_LOCAL_PUBLIC_NEWS_SUCCESS';
export const LOAD_LOCAL_PUBLIC_NEWS_FAILED = 'LOAD_LOCAL_PUBLIC_NEWS_FAILED';
export const FETCH_PUBLIC_NEWS_FAILED_NO_AUTH = 'FETCH_PUBLIC_NEWS_FAILED_NO_AUTH';
export const RECEIVE_NEW_MESSAGES = 'RECEIVE_NEW_MESSAGES';